FORMAT: 1A
HOST: http://52.27.31.124/project/

# Weekend-Planner

Weekend Planner is an API made for Practeon for making weekend trip with low budget by adding more people in the trip.


## Profile of user [/user/profile/]
### Show the details[GET]

+ Response 200 (application/json)

        [
           {
            "userId": 2,
            "name": "Ankit Singh",
            "emailId": "ankit.singh@practo.com",
            "mobile": "9125551187"
            }
        ]

## List All Trip [/trip/all]
This is page where alll the trips happeing in the coming dates will be diplayed.
### List all the Trips [GET]

+ Response 200 (application/json)

        [
            {
                "trip_id": "10",
                "trip-name": "Trip to...",
                "when": "25/09/2016",
                "where": "Nandi Hills",
                "type": "Hill station",
                "number_days": "3",
                "space_left": "3"
            }
            {
                "trip_id": "15",
                "trip-name": "Trip to...",
                "when": "26/09/2016",
                "where": "Thanjavur",
                "type": "Temple",
                "number_days": "1",
                "space_left": "5"
            }
        ]

## List Trips based on filters [/trip/filter/{filters}]
### List Trips based on filters[GET]
+ Response 200 (application/json)

        [
            {
                "trip_id": "10",
                "trip-name": "Trip to...",
                "when": "25/09/2016",
                "where": "Nandi Hills",
                "type": "Hill station",
                "number_days": "3",
                "space_left": "3"
            }
            {
                "trip_id": "15",
                "trip-name": "Trip to...",
                "when": "26/09/2016",
                "where": "Thanjavur",
                "type": "Temple",
                "number_days": "1",
                "space_left": "5"
            }
        ]
## Signup for Trip [/trip/all/{signup}]
### Signup for Trip [POST]

+ Request (application/json)

        {
            "trip_id": "20",
            "user": "xyz@gmail.com"
        }
+ Response 201 (application/json)

    + Headers

            Location: /dashboard/20

    + Body

            {
                "message": "Signed Up for the Trip"
            }
## Post a Trip [/trip/user]
Post a new trip.

### Post a Trip [POST]

+ Request (application/json)

        {
            "trip-name": "Trip to ...",
            "user": "xyz@gmail.com",
            "when": "24/08/2016",
            "where": "Nandi Hills",
            "people_going":"4",
            "extra_space": "3",
            "average_cost": "900",
            "number_days": "2"
        }
+ Response 201 (application/json)

    + Headers

            Location: /dashboard/21

    + Body

            {
                "message": "Trip posted succesfully"
            }
            
            
## Editing already posted trips [/trip/user/{trip_id}]
Making change to already posted trips.
### Change the Trip details[PUT]
+ Request (application/json)

        {
            "trip_id": "21",
            "user": "xyz@gmail.com",
            "when": "28/08/2016",
            "where": "Nandi Hills",
            "people_going":"4",
            "extra_space": "3",
            "average_cost": "900",
            "number_days": "2"
        }
+ Response 201 (application/json)

    + Headers

            Location: /dashboard/21

    + Body

            {
                "message": "Trip details successfully changed"
            }


## Deleting already posted trips [/trip/user/{id}]
Deleting laready posted trips.
### Delete the Trip[DELETE]
+ Request (application/json)

        {
            "trip_id": "21"
        }
+ Response 201 (application/json)

    + Headers

            Location: /dashboard/21

    + Body

            {
                "message": "Trip deleted Successfully"
            }