FORMAT: 1A
http://www.singhankit.me/wp/
# Weekend-Planner

Weekend Planner is an API made for Practeon for making weekend trip with low budget by adding more people in the trip.


## Profile of user [/user/{id}]
### Show the details[GET]

+ Response 200 (application/json)

        [
           {
            "userId": 2,
            "name": "Ankit Singh",
            "emailId": "ankit.singh@practo.com",
            "mobile": "9125551187"
            }
        ]

## List All Trip [/trip/all]
This is page where alll the trips happeing in the coming dates will be diplayed.
### List all the Trips [GET]

+ Response 200 (application/json)

        [
            {
                "tripId": 6,
                "averageCost": 3000,
                "goingDate": 1473206400000,
                "goingPeople": 3,
                "numOfDay": 3,
                "spaceLeft": 2,
                "tripName": "Trip to Ramanagara",
                "isDeleted": 0,
                "userName": "Ankit Singh",
                "destinationLocation": "Ramanagara",
                "destinationType": "Trekking",
                "userEmailId": "ankit.singh.2016@iitkalumni.org",
                "userId": 3
}
            {
                "tripId": 8,
                "averageCost": 4000,
                "createdAt": null,
                "goingDate": 1473206400000,
                "goingPeople": 3,
                "modifiedAt": null,
                "numOfDay": 1,
                "spaceLeft": 2,
                "tripName": "Trip to Bhoga Nandeeshwar",
                "isDeleted": 0,
                "userName": "Ankit Singh",
                "destinationLocation": "Bhoga Nandeeshwara Temple - Nandi",
                "destinationType": "Historical-Heritage",
                "userEmailId": "ankitsin37@gmail.com",
                "userId": 1
            }
        ]

## List Trips based on filters [/trip/filter/{filters}]
### List Trips based on filters[GET]
+ Response 200 (application/json)

        [
            {
                "tripId": 6,
                "averageCost": 3000,
                "createdAt": null,
                "goingDate": 1473206400000,
                "goingPeople": 3,
                "modifiedAt": null,
                "numOfDay": 3,
                "spaceLeft": 2,
                "tripName": "Trip to Ramanagara",
                "isDeleted": 0,
                "userName": "Ankit Singh",
                "destinationLocation": "Ramanagara",
                "destinationType": "Trekking",
                "userEmailId": "ankit.singh.2016@iitkalumni.org",
                "userId": 3
            }
            {
                "tripId": 4,
                "averageCost": 1111,
                "createdAt": null,
                "goingDate": 1473811200000,
                "goingPeople": 2,
                "modifiedAt": null,
                "numOfDay": 3,
                "spaceLeft": 2,
                "tripName": "Trip to Ramanagara",
                "isDeleted": 0,
                "userName": "Ankit Singh",
                "destinationLocation": "Ramanagara",
                "destinationType": "Trekking",
                "userEmailId": "ankitsin37@gmail.com",
                "userId": 1
            }
        ]
## Signup for Trip [/trip/all/{signup}]
### Signup for Trip [POST]

+ Request (application/json)

        {
            "trip_id": "20",
            "user": "xyz@gmail.com"
        }
+ Response 201 (application/json)

    + Headers

            Location: /dashboard/20

    + Body

            {
                "message": "Signed Up for the Trip"
            }
## Post a Trip [/trip/user]
Post a new trip.

### Post a Trip [POST]

+ Request (application/json)

        {
            "trip-name": "Trip to ...",
            "user": "xyz@gmail.com",
            "goingDate": "24/08/2016",
            "destinationName": "Nandi Hills",
            "people_going":"4",
            "spaceLeft": "3",
            "averageCost": "900",
            "numberOfDays": "2"
        }
+ Response 201 (application/json)

    + Headers

            Location: /dashboard/21

    + Body

            {
                "message": "Trip posted succesfully"
            }
            
            
## Editing already posted trips [/trip/user/{trip_id}]
Making change to already posted trips.
### Change the Trip details[PUT]
+ Request (application/json)

        {
            "trip_id": "21",
            "user": "xyz@gmail.com",
            "goingDate": "28/08/2016",
            "destinationName": "Nandi Hills",
            "people_going":"4",
            "spaceLeft": "3",
            "averageCost": "900",
            "numberOfDays": "2"
        }
+ Response 201 (application/json)

    + Headers

            Location: /dashboard/21

    + Body

            {
                "message": "Trip details successfully changed"
            }


## Deleting already posted trips [/trip/user/{id}]
Deleting laready posted trips.
### Delete the Trip[DELETE]
+ Request (application/json)

        {
            "trip_id": "21"
        }
+ Response 201 (application/json)

    + Headers

            Location: /dashboard/21

    + Body

            {
                "message": "Trip deleted Successfully"
            }


## Get Destination Destails[/destination/all]
### Get All Destination[GET]
+ Response 200 (application/json)

        [
            {
                "destinationId": "1",
                "distance": "43",
                "location": "Muthyala Maduvu",
                "type": "Waterfall"
            }
            {
                "destinationId": "2",
                "distance": "23",
                "location": "Bannerghatta National Park",
                "type": "Wildlife"
            }
        ]
        

## Get Destination Destails by Id[/destination/{3}]
### Get Destination by Id[GET]
+ Response 200 (application/json)

        [
            {
                "destinationId": "3",
                "distance": "54",
                "location": "Ramanagara",
                "type": "Trekking"
            }
            
        ]